### PR TITLE
Added conversions between designators and JSON.

### PR DESCRIPTION
**Pull request by wiedemeyer**
Conversions to an from JSON, so that there is a easy interface for python code.

### CODE REVIEW

**Comment by fairlight1337** [comment]
Looks good from my point of view. I don't see RapidJSON in the debs, though. Whats the usual channel to acquire it, @wiedemeyer?

Also, before merging this, I'd vote for merging the changes from [cram2's changes](https://github.com/cram2/designator_integration) back into [code-iai's base repository](https://github.com/code-iai/designator_integration). @gaya-, the changes in cram2's fork are purely for compatibility with the new CRAM, is that right? If there is no objection from anyone else, I think we should go for pulling that in, optionally marking the current state of the designator integration in code-iai with a tag.

Let's do this timely; otherwise, the forks will diverge too strongly.

Might affect @gheorghelisca, @airballking, @yazdani, and @bbrieber as well.

**Comment by gaya-** [comment]
> Also, before merging this, I'd vote for merging the changes from cram2's changes back into code-iai's base repository. @gaya-, the changes in cram2's fork are purely for compatibility with the new CRAM, is that right? If there is no objection from anyone else, I think we should go for pulling that in, optionally marking the current state of the designator integration in code-iai with a tag.

Here are the changes for you to pull in: https://github.com/code-iai/designator_integration/pull/10

**Comment by wiedemeyer** [comment]
Instead of an submodule in designator_integration, we could also create a ros_rapidjson wrapper package with a submodule, that provides rapidJSON. Then we could also use it in other packages.
Or the less beautiful way would be to export the rapidJSON include folder from designator_integration.

**Comment by fairlight1337** [comment]
I merged in the PR from @gaya-, works fine. I'll now look into merging this one in.

**Pull request merged**
