### PR TITLE
Allow proper serialization of cl-tf:3d-vector

### PR DESCRIPTION
**Pull request by fairlight1337**

### CODE REVIEW

**Comment by airballking** [comment]
Quick questions: ```designator_integration_msgs/KeyValuePair.msg``` has a slot of type ```geometry_msgs/Point```. I would have used that one instead of transmission via a value-array. Is there a difference between both approaches?

**Comment by fairlight1337** [comment]
Using the slot would require signifying in the designator that this is indeed a `point`, rather than a `list` of components (which seemed more trivial to me). Sometimes the dimensions only have two components, such as e.g. cylinders; this would require extra handling on which fields (`x`, `y`, `z`) to use for which component in these.

But I see your point. You created the serialization for `point` - would it make sense to recurse into the serialization function using an intermediate `point` structure including the vector's `x`, `y`, `z`?

Funny, `point` is actually a sub type of `3d-vector`:

```lisp
(deftype point ()
  '(or 3d-vector (vector vector-coefficient 3)))
```

So, semantically it should actually be the other way around.

Bottomline: I agree, as the `point` probably also annotates the axis field, doesn't it? Like `(x 0.5)`?

**Comment by airballking** [comment]
My thinking never got so elaborate. ;)

I only wanted to preserve the type information during serialization/de-serialization. I think if the sending side has type checking for this datum to ensure it has 3 values, it would be nice if the receiving end had the same feature available. That's all.

**Comment by fairlight1337** [comment]
I see.

I'd like to have it in for now (no time for big refactoring of all that atm), so I can also just stay on that branch. We can see about making it cleaner after the demo. So just ignore the PR for now.

**Comment by airballking** [comment]
OK, then.

**Pull request merged**
