### PR TITLE
added flag, for not setting parent during serialization, but setting …

### PR DESCRIPTION
**Pull request by bbferka**
…it before with the semanitcs of level. Workaroung for the bug in knowrob_cram where readvertising the designators from the mongodb changes the fields previous semantics

### CODE REVIEW

**Comment by bbferka** [comment]
Could someone pls check if this fix breaks working code? (It shouldn't since the added param's default is to create parent IDs during serialization

**Comment by airballking** [comment]
For what it's worth: Just from looking at the code I'd say it is not breaking working code.

**Comment by fairlight1337** [comment]
Of course semantically that's not the right place to fix knowrob_cram's bugs ;). Thanks for the fix anyway, looks okay. Haven't tried it though.

**Comment by bbferka** [comment]
@fairlight1337  yes, I totally agree. I was not happy about having to touch this code, but it seams it is the quickest way for not to fix this without breaking anything:(

**Comment by fairlight1337** [comment]
There were changes in the master branch, I merged them in. Its working fine now, I'll merge it.

**Pull request merged**
